steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER%%-vlaanderen}/${CI_REPO_NAME}"
      tags: "${CI_COMMIT_BRANCH}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [development]